### ISSUE TITLE
[flutter_math_fork] Error: Too few positional arguments: 4 required, 3 given

### ISSUE THREAD

**Issue by jlubeck** [simpleclub/firebase-rules-helper#6]
Sorry to polute this repo with a bug on another one, but it looks like the fork you have for flutter_math_fork doesn't allow creating new issues there.

Looks like with the latest version of Flutter, this fork is broken, which in return broke the package `flutter_html` that is using that fork as a dependency: https://github.com/Sub6Resources/flutter_html/issues/732

The issue it self is that when trying to build the app, we get this error:

```
 ../../../.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.3.3/lib/src/widgets/selection/handle_overlay.dart:197:58: Error: Too few positional arguments: 4 required, 3 given.
                  child: widget.selectionControls.buildHandle(
```

So Hopefully since you are under the same organization you can let the devs on that fork know about this issue? 

Let me know if there is a better place for this. 

Thank you!

**Comment by jlubeck** [comment]
I created a PR here as well: https://github.com/simpleclub-extended/flutter_math/pull/3

**Comment by IchordeDionysos** [comment]
Let's close this issue as it's already fixed in `flutter_math_fork` :)

**Comment by jlubeck** [comment]
> Let's close this issue as it's already fixed in `flutter_math_fork` :)

Thank you for relaying!
